### ISSUE TITLE
Choosing CSS literal always fails on the first try, succeeds on second and color picker doesn't set color

### ISSUE THREAD

**Issue by adambair** [benknight/hue-alfred-workflow#30]
First off -- THIS IS AWESOME. I'm a software developer and just took the plunge and setup my house with hue lights... this alfred workflow is going to kick ass :)

That said, I've run into:
- I'm unable to use most css literal color names even though they seem to be defined in the source code. Here's an example

![](https://cl.ly/3n1f2i3V3U3K/Image%202016-10-25%20at%204.36.28%20PM.png)

which results in

![](https://cl.ly/1i181l1o0b0F/Image%202016-10-25%20at%204.39.43%20PM.png)

on the first attempt... if I run the exact same command again... the lights change no problem...
- I'm unable to use the color picker to choose light colors -- The picker comes up, I select a color, then click 'pick' and nothing happens, Alfred goes away, lights don't change, no messages.

**Comment by benknight** [comment]
@adambair this is because of the delay in script execution that occurs each time you type a character.  If you wait a half second or so after typing the color, then press enter, it should work every time.  This is a bummer I admit, especially as I'm a fast typer myself.  I'll look into fixing this in the next update.

**Comment by adambair** [comment]
Awesome! Thanks for the easy work around -- I totally get it, not a big deal -- most appreciated. Your Alfred/Hue integration is *fantastic*.

While I'm not a Python developer, Ruby here:

[![The Least Surprised](https://cl.ly/3N3O43412a0a/Image%202016-10-28%20at%208.51.19%20AM.png)](https://www.youtube.com/watch?v=mXZ_htL1rOI)

...I'm curious about where the delay is located in the code so I can take a peek (and perhaps take a stab at it myself).

Either way, great work -- thanks!

**Comment by benknight** [comment]
@adambair See the "hue" script filter.

Each type you type a character it executes:

```bash
python -m logic.filters "{query}"
```

The script outputs the XML that Alfred uses to show results.

So as you're typing "purple" for example, there is a split second where after you type the final "e", the "Set color to" item has its action set to "lights:1:color:purpl", and if you hit enter too soon it will think you entered "purpl" which is invalid.  Wait a tick more and it's finally updated to "purple" at which point it works.

I was hoping to get around this issue by tinkering with the "Script Behavior" settings on the "hue" filter, which I currently have as:

![image](https://cloud.githubusercontent.com/assets/786691/19816106/ce2cdaf0-9cfa-11e6-97b6-7a7c3eaf8d2b.png)

But none of those configurations seem to help or even apply really.  The problem is in the script execution time for the Python filter script.

**Comment by adambair** [comment]
Sweet!

**Comment by benknight** [comment]
@adambair in the next version (2.4.2) I've "fixed" this by making it impossible to hit the enter key until it recognizes that the input is a valid color string.
