### ISSUE TITLE
Ability to specify groups by name

### ISSUE THREAD

**Issue by adambair** [benknight/hue-alfred-workflow#40]
I used quite a while ago and it's still amazing. Thanks for all your (and contributor's) hard work.

This is more of a feature request... It would be super helpful if you could select groups based on their actual name instead of having to know their group number.

example:

`hue groups:dining:bri:25`

instead of:

`hue groups:3:bri:25`

If there's a way to do this already -- my apologies, I didn't see any docs or info on it...

Most appreciated,
-a

**Comment by RishabSwift** [comment]
Also would like to suggest to include like a toggle one. 

such as groups:3:toggle

**Comment by benknight** [comment]
I debated about this but went with the group ID for a few reasons.  First it doesn't change, unlike the name.  Second that way the action string doesn't have any spaces in it, which makes things easier to deal with since the script uses spaces to split the string into multiple commands.

If you watch the notification message after you perform an action or open history.txt from the workflow configuration it should make it easy to copy action strings for setting things like groups and scenes.

Let me know if that helps!
