### ISSUE TITLE
Capability to cycle scenes

### ISSUE THREAD

**Issue by rgrtht** [benknight/hue-alfred-workflow#41]
Don't know how popular this would be - just a suggestion. I would find it very handy, but I'm not even sure if it's possible. Sorry - I didn't really think much beyond suggesting it. :/

**Comment by benknight** [comment]
That's a cool idea, but maybe a bit beyond the scope here.  There are probably other Hue apps out there that do that.  

I'm not actually sure if it's possible because this would require having a script running in the background, sending a command to the bridge on a set interval.  I think when Alfred executes scripts, they terminate after a set time out.
